package com.android.identity.device

data class DeviceAttestationResult(
    /**
     * Identifier for the opaque private key generated by [DeviceCheck.generateAttestation]
     * method
     */
    val deviceAttestationId: String,

    /**
     * Data that proves the platform integrity.
     */
    val deviceAttestation: DeviceAttestation
)