package com.android.identity.asn1

enum class ASN1StringTag(val tagNumber: Int) {
    UTF8_STRING_TAG_NUMBER(0x0c),
    NUMERIC_STRING_TAG_NUMBER(0x12),
    PRINTABLE_STRING_TAG_NUMBER(0x13),
    TELETEX_STRING_TAG_NUMBER(0x14),
    VIDEOTEX_STRING_TAG_NUMBER(0x15),
    IA5_STRING_TAG_NUMBER(0x16),
    GRAPHIC_STRING_TAG_NUMBER(0x19),
    VISIBLE_STRING_TAG_NUMBER(0x1a),
    GENERAL_STRING_TAG_NUMBER(0x1b),
    UNIVERSAL_STRING_TAG_NUMBER(0x1c),
    CHARACTER_STRING_TAG_NUMBER(0x1d),
    BMP_STRING_TAG_NUMBER(0x1e)
}