name: Trigger Docs Update

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docusaurus repository workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          repository: openmobilehub/developer-multipaz-website/
          event-type: kotlin-repo-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
